// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgDeckLab.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MtgDeckLab.Infrastructure.Migrations
{
    [DbContext(typeof(MtgDeckLabDbContext))]
    [Migration("20260904013327_AddColorArrayColumns")]
    partial class AddColorArrayColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MtgDeckLab.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cmc")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("cmc");

                    b.Property<string>("Loyalty")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("loyalty");

                    b.Property<string>("ManaCost")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mana_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("OracleText")
                        .HasColumnType("text")
                        .HasColumnName("oracle_text");

                    b.Property<string>("Power")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("power");

                    b.Property<decimal?>("PriceUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_usd");

                    b.Property<decimal?>("PriceUsdFoil")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_usd_foil");

                    b.Property<Guid>("ScryfallId")
                        .HasColumnType("uuid")
                        .HasColumnName("scryfall_id");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("set_code");

                    b.Property<string>("Toughness")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("toughness");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type_line");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<int[]>("_colorIdentity")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("color_identity");

                    b.PrimitiveCollection<int[]>("_colors")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("colors");

                    b.Property<string>("_subtypes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtypes");

                    b.Property<string>("_supertypes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supertypes");

                    b.Property<string>("_types")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("types");

                    b.HasKey("Id");

                    b.HasIndex("ScryfallId")
                        .IsUnique();

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("MtgDeckLab.Domain.Entities.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("decks", (string)null);
                });

            modelBuilder.Entity("MtgDeckLab.Domain.Entities.DeckEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<bool>("IsCommander")
                        .HasColumnType("boolean")
                        .HasColumnName("is_commander");

                    b.Property<bool>("IsSideboard")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sideboard");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("DeckId", "CardId", "IsCommander", "IsSideboard")
                        .IsUnique();

                    b.ToTable("deck_entries", (string)null);
                });

            modelBuilder.Entity("MtgDeckLab.Domain.Entities.FinanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<decimal>("TotalCostUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_cost_usd");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("finance_snapshots", (string)null);
                });

            modelBuilder.Entity("MtgDeckLab.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MtgDeckLab.Domain.Entities.DeckEntry", b =>
                {
                    b.HasOne("MtgDeckLab.Domain.Entities.Deck", null)
                        .WithMany("Entries")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MtgDeckLab.Domain.Entities.Deck", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
